server {
    listen 3000;
    server_name localhost;
    charset UTF-8;
    root /var/www/html/public;
    index index.php index.html;

    client_max_body_size 10m;
    client_body_buffer_size 10m;

    server_tokens off;
    fastcgi_hide_header X-Powered-By;

    location / {
        try_files $uri $uri/ /index.php?/$request_uri;
    }

    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param CI_ENV development;
    }

    location ~ .*\.(html?|jpe?g|gif|png|svg|css|js|ico|swf|inc) {
        expires 1d;
        access_log off;
    }

    location = /favicon.ico {
        empty_gif;
        access_log off;
        log_not_found off;
    }
}
